export const FETCH_POKEMONS = 'FETCH_POKEMONS';
export const FETCH_POKEMON = 'FETCH_POKEMON';
export const CAUGHT_POKEMON = 'CATCH_POKEMON';
export const PUT_POKEMON = 'PUT_POKEMON';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const RESET_POKEMONS = "RESET_POKEMONS";
export const FETCH_PAGE = "FETCH_NEXT_PAGE"
export const RESET_PAGE = "RESET_PAGE";
export const RESET_CAUGHT_POKEMONS = "RESET_CAUGHT_POKEMONS"

export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
